config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from notes.views import index
"""
통합페이지 구성
1. 인덱스 페이지 : 뭐하는 페이지인지 간단한 설명, 로그인으로 넘어갈 수 있는 구조
2. 로그인 페이지
3. 로그아웃 페이지, 일정시간 후 자동으로 인덱스 페이지로 넘기기/html의 메타태그 사용
4. 노트 앱으로 접속
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('notes/', include('notes.urls', namespace = 'notes')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path("__reload__/", include("django_browser_reload.urls")),

    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

notes/urls.py
from django.urls import path
from .views import ctgr2_create, main_page, Pcategory_page, Scategory_page, \
    create_page, detail_page, edit_page, delete_page, \
    ctgr_view, ctgr1_create, ctgr1_edit, ctgr1_delete, \
    ctgr2_create, ctgr2_edit, ctgr2_delete
from .views import TagCloudTV, TaggedObjectLV

app_name = 'notes'

"""
필요한 페이지 
1. 로그인 후 보여줄 메인페이지 : 작성된 전체글, 부모 카테고리 지정 링크
2. 부모 카테고리 : 부모 카테고리에 포함된 모든 글 및 자식 카테고리 지정 링크
3. 자식 카테고리 : 자식 카테고리에 포함된 모든 글 링크
4. 글 쓰기 : 새로운 글 쓰기
5. 개별글 보기 : 작성된 글 상세보기 링크
6. 개별글 수정 : 작성된 글 수정 링크
7. 개별글 삭제 : 작성된 글 삭제 페이지, Hard-Delete
8. 태그별 보기 : 작성된 글 중에서 태그에 해당되는 글 리스트 출력
"""

urlpatterns = [
    # 기본 View 페이지
    path('main/', main_page, name='main_page'),
    path('category/<str:cate_name>', Pcategory_page, name='Pcategory_page'),
    path('category/category2/<str:cate2_name>', Scategory_page, name='Scategory_page'),
    
    # 노트 CRUD
    path('new/', create_page, name='create_page'),
    path('<int:id>/', detail_page, name='detail_page'),
    path('<int:id>/edit/', edit_page, name='edit_page'),
    path('<int:id>/delete/', delete_page, name='delete_page'),

    # 카테고리 CRUD
    path('ctgymanage/', ctgr_view, name='ct_manage_view'),
    path('ctgymanage/ctgr1/new/', ctgr1_create, name='ct1_manage_create'),
    path('ctgymanage/ctgr1/edit/<int:id>', ctgr1_edit, name='ct1_manage_edit'),
    path('ctgymanage/ctgr1/del/<int:id>', ctgr1_delete, name='ct1_manage_del'),
    path('ctgymanage/ctgr2/new/', ctgr2_create, name='ct2_manage_create'),
    path('ctgymanage/ctgr2/edit/<int:id>', ctgr2_edit, name='ct2_manage_edit'),
    path('ctgymanage/ctgr2/del/<int:id>', ctgr2_delete, name='ct2_manage_del'),

    #Taggit 모듈 사용, Tag 페이지 별도 구성
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>',TaggedObjectLV.as_view(), name='tagged_object_list'),
]

notes/models.py
from django.db import models
from django.conf import settings

from taggit.managers import TaggableManager

#모델로써 제작 되어야 할 것들 : 노트본문, 카테고리 항목, 하위 카테고리 항목

# 장고에서 제공하는 User Model 불러오기
User = settings.AUTH_USER_MODEL

class Category(models.Model): # 상위 카테고리
    class Meta: # 클래스의 이름을 지정
        verbose_name = '상위 카테고리'
        verbose_name_plural = '상위 카테고리'

    # 상위 카테고리 이름 지정
    cate_name = models.CharField(verbose_name='카테고리', max_length=20, unique=True)
    # 카테고리 생성자 지정(22.05.16)
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='Cate1_Created_User', null=True, blank=True)

    def __str__(self): # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.cate_name}'

class Category2(models.Model): # 하위 카테고리
    class Meta: # 클래스의 이름을 지정
        verbose_name = '하위 카테고리'
        verbose_name_plural = '하위 카테고리'

    # 상위 카테고리 확인
    P_cate_name = models.ForeignKey(Category, verbose_name='상위 카테고리', on_delete=models.CASCADE, related_name='Cate2_Parents_name')
    # 하위 카테고리 이름 지정
    cate2_name = models.CharField(verbose_name='하위 카테고리', max_length=20, null=True, blank=True, unique=True)
    # 카테고리 생성자 지정(22.05.16)
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='Cate2_Created_User', null=True, blank=True)

    def __str__(self): # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.cate2_name}'

class Note(models.Model):
    # 노트에 들어갈 내용들 - 제목, 내용, 작성시간, 작성자, 참조 링크, 카테고리

    class Meta: # 클래스의 이름을 지정
        verbose_name = '노트'
        verbose_name_plural = '노트'

    # 노트 카테고리 : 노트에 지정될 카테고리 항목, 2차 카테고리에 연결
    categories = models.ForeignKey(Category2, verbose_name='카테고리', on_delete=models.CASCADE, related_name='Note_Category_name')
    # 제목 : 글의 제목 / 인덱스 페이지, 전체글 보기, 카테고리별 글 보기, 개별글 보기에 표기
    title = models.CharField(verbose_name='제목', max_length=100) 
    # 내용 : 글의 본문 / 개별글 보기에만 표기
    contents = models.TextField(verbose_name='본문')
    # 작성시간 : 글이 작성된 시간 / 생성후 변경되면 안되므로 auto_now_add 사용
    created_at = models.DateTimeField(verbose_name='작성시간', auto_now_add=True)
    # 수정시간 : 글이 수정된 시간 / 수정될때마다 변경되어야 하므로 auto_now 사용
    modified_at = models.DateTimeField(verbose_name='수정시간', auto_now=True)
    # 작성자 : 글쓴이 / 장고에서 제공하는 User Model을 사용하기
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='Note_Created_User')
    # 참조링크 : CharField의 확장, 편리한 유효성 검사를 URLField를 사용. 반드시 필요한 항목은 아님
    ref_link = models.URLField(verbose_name='참조링크', max_length=300, null=True, blank=True)
    # 태그 : 외부 모듈인 Taggit 사용하여 추가, 태그별 검색을 할 수 있도록 추가
    tags = TaggableManager(verbose_name="태그", help_text="콤마(,)로 구분합니다.", blank=True, related_name='Note_tags')

# Tagsave 비활성화, Taggit 사용

notes/forms.py
'''
글 생성, 수정, 읽기 폼 필요
카테고리 생성, 읽기, 수정 폼 ->(선결) Models.py 수정해서 카테고리마다 유저를 받도록 변경
'''

from django import forms

from .models import Note, Category, Category2

# 노트
class NoteBaseForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'

class NoteCreateForm(NoteBaseForm):
    class Meta(NoteBaseForm.Meta):
        fields = ['categories', 'title', 'contents', 'ref_link','tags',]

class NoteEditForm(NoteBaseForm):
    class Meta(NoteBaseForm.Meta):
        fields = ['categories', 'title', 'contents', 'ref_link','tags',]

# 상위 카테고리
class Ctgr1BaseForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class Ctgr1CreateForm(Ctgr1BaseForm):
    class Meta(Ctgr1BaseForm.Meta):
        fields = ['cate_name',]

class Ctgr1EditForm(Ctgr1BaseForm):
    class Meta(Ctgr1BaseForm.Meta):
        fields = ['cate_name',]

# 하위 카테고리
class Ctgr2BaseForm(forms.ModelForm):
    class Meta:
        model = Category2
        fields = '__all__'

class Ctgr2CreateForm(Ctgr2BaseForm):
    class Meta(Ctgr2BaseForm.Meta):
        fields = ['P_cate_name', 'cate2_name',]

class Ctgr2EditForm(Ctgr2BaseForm):
    class Meta(Ctgr2BaseForm.Meta):
        fields = ['P_cate_name', 'cate2_name',]

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.core.paginator import Paginator
from django.views.generic import ListView, TemplateView

from .models import Category, Category2, Note
from .forms import NoteCreateForm, NoteEditForm, Ctgr1CreateForm, Ctgr1EditForm, Ctgr2CreateForm, Ctgr2EditForm

""" 작성해야할 views
    인덱스, 로그인/로그아웃, 메인, 카테고리1,2차, 생성/읽기/수정/삭제(CRUD) 페이지
    # path('main/', main_page, name='main_page'),
    # path('category/', Pcategory_page, name='Pcategory_page'),
    # path('category/category2/', Scategory_page, name='Scategory_page'),
    # path('new/', create_page, name='create_page'),
    # path('<int:id>/', detail_page, name='detail_page'),
    # path('<int:id>/edit/', edit_page, name='edit_page'),
    # path('<int:id>/delete/', delete_page, name='delete_page'),
    # path('', index, name='index'),
    # path('login/', login, name='login'),
    # path('logout/', logout, name='logout'),
    # path('tagsearch/',Tsearch_page, name='Tsearch_page')
"""

def index(request): # 뭐하는 페이지인지 간단한 설명, 로그인으로 넘어갈 수 있는 구조
    # 로그인 유도 기본 화면 출력
    # 데이터 유효성 검사 - 로그인 상태인지 확인
    # 비지니스 로직 - 비 로그인 상태/ 로그인 상태 구분
    # 응답 - 비로그인: 인덱스 페이지 / 로그인: 노트 메인페이지
    if not request.session.session_key:
        #print('로그인이 되어 있지 않습니다.')
        return render(request, 'index.html',{'form':AuthenticationForm(),})
    else:
        #print(f'{request.user.username}님이 로그인 되어 있습니다.')
        return redirect('notes:main_page')

@login_required
def main_page(request): # 로그인 후 보여줄 메인페이지 : 작성된 전체글, 부모 카테고리 지정 링크
    # 전체글 게시할 메인 페이지
    # 데이터 유효성 검사 - 로그인 된 유저 데이터 확인
    # 비지니스 로직 - 로그인 된 유저가 작성한 게시글 불러오기 및 카테고리 불러오기
    # 응답 - 작성한 게시글 및 상위 카테고리 표시, 최신글 순서
    current_user = request.user

    note_list = Note.objects.filter(created_by = current_user).order_by('-created_at')
    ctgy_list = Category.objects.filter(created_by = current_user).order_by('id')

    paging = Paginator(note_list, 20) # 페이지 나누기 추가, (object_list, per_page)
    page_num = request.GET.get('page') # 페이지 번호 가져오기
    note_list_index = paging.get_page(page_num) # 페이지 인덱싱
    context = {
        'list_view_page':'On',
        'note_page_list':note_list_index,
        'ctgy_list':ctgy_list,
        }
    return render(request, 'notes/main.html', context)

@login_required
def Pcategory_page(request, cate_name): # 상위 카테고리 : 상위 카테고리에 포함된 모든 글 및 자식 카테고리 지정 링크
    # 상위 카테고리 표시 페이지
    # 데이터 유효성 검사 - 로그인 유저 데이터 + 선택한 상위 카테고리 명 확인
    # 비지니스 로직 - 해당 카테고리의 로그인 유저 작성글 불러오기
    # 응답 - 작성한 게시글 및 하위 카테고리 표시
    current_user = request.user
    current_category = Category.objects.get(cate_name = cate_name)

    note_list = Note.objects.filter(created_by = current_user).filter(categories__P_cate_name = current_category).order_by('-created_at')
    ctgy2_list = Category2.objects.filter(created_by = current_user).filter(P_cate_name = current_category).order_by('id')

    paging = Paginator(note_list, 20) # 페이지 나누기 추가, (object_list, per_page)
    page_num = request.GET.get('page') # 페이지 번호 가져오기
    note_list_index = paging.get_page(page_num) # 페이지 인덱싱

    context = {
        'list_view_page':'On',
        'ctgy_now':current_category,
        'note_page_list':note_list_index,
        'ctgy_list':ctgy2_list,
    }

    return render(request, 'notes/category.html', context)

@login_required
def Scategory_page(request, cate2_name): # 하위 카테고리 : 하위 카테고리에 포함된 모든 글 링크
    # 하위 카테고리 표시 페이지
    # 데이터 유효성 검사 - 로그인 유저 데이터 + 선택한 하위 카테고리 명 확인
    # 비지니스 로직 - 해당 카테고리의 로그인 유저 작성글 불러오기
    # 응답 - 작성한 게시글 표시
    current_user = request.user
    current_category = Category2.objects.get(cate2_name = cate2_name)

    note_list = Note.objects.filter(created_by = current_user).filter(categories = current_category).order_by('-created_at')

    paging = Paginator(note_list, 20) # 페이지 나누기 추가, (object_list, per_page)
    page_num = request.GET.get('page') # 페이지 번호 가져오기
    note_list_index = paging.get_page(page_num) # 페이지 인덱싱

    context = {
        'list_view_page':'On',
        'ctgy_now':current_category,
        'note_page_list':note_list_index,
    }

    return render(request, 'notes/category.html', context)

@login_required
def create_page(request): # 글 쓰기 : 새로운 글 쓰기
    # GET: 글 작성 페이지 render
    # POST 
    # 데이터 유효성 검사  
    #  반드시 들어가야할 몇가지 항목이 작성되어 있는가, is_valid를 사용 // 카테고리, 제목, 본문, 참조링크, 태그 읽어오기. cleaned_data
    #  태그 작성시 ,(콤마)로 구분짓고, 개별 단위로 생성(split)
    # 비지니스 로직 - 읽어온 항목들을 DB에 생성하기
    # 응답 - main-page로 redirect
    if request.method=='GET':
        form = NoteCreateForm()
        context = {
            'forms':form,
            'notepage':'notes'
        }
        return render(request, 'notes/create.html', context)
    else:
        form = NoteCreateForm(request.POST)
        if form.is_valid():
            new_note = Note.objects.create(
                categories = form.cleaned_data['categories'],
                title = form.cleaned_data['title'],
                contents = form.cleaned_data['contents'],
                ref_link = form.cleaned_data['ref_link'],
                created_by = request.user,
            )
            f_tags = form.cleaned_data['tags']
            for f_tag in f_tags:
                new_note.tags.add(f_tag)

            """ Official Doc. Method
            new_note = form.save(commit=False) # form을 구성하기, DB엔 저장하지 않음
            new_note.categories = form.cleaned_data['categories']
            new_note.title = form.cleaned_data['title']
            new_note.contents = form.cleaned_data['contents']
            new_note.ref_link = form.cleaned_data['ref_link']
            new_note.created_by = request.user
            new_note.save() # form에 적힌 내용을 저장하기
            form.save_m2m() # Many to Many, 다대다 연결
            """
        else:
            return redirect('notes:create_page')
        return redirect('notes:main_page')

@login_required
def detail_page(request, id): # 개별글 보기 : 작성된 글 상세보기 링크
    # 데이터 유효성 검사 - 선택한 게시글 아이디 확인 및 읽어오기
    # 비지니스 로직 - 해당 아이디의 카테고리, 제목, 본문, 참조링크, 태그등을 html에 전달
    # 응답 - 전달된 데이터로 render
    user = request.user
    try:
        note = Note.objects.get(id=id)
    except Note.DoesNotExist:
        return redirect('notes:main_page')
    if user != note.created_by:
        return redirect('notes:main_page')
    context = {
        'note':note,
        }
    return render(request, 'notes/detail.html', context)

@login_required
def edit_page(request, id): # 개별글 수정 : 작성된 글 수정 링크
    # GET : 기존 데이터 표기, render
    # POST
    # 데이터 유효성 검사 - 수정하는 게시글 내용 읽어오기
    # 비지니스 로직 - 신규 데이터를 해당되는 모델에 입력하고, 저장
    # 응답 - 해당되는 detail 페이지로 redirect
    ## Tag 수정할때 변경되는 로직이 필요한데?
    target = get_object_or_404(Note, id=id, created_by=request.user)
    if request.method=='GET':
        forms = NoteEditForm(instance= target)
        return render(request, 'notes/create.html', {'forms':forms,'notepage':'on'})
    else:
        forms = NoteEditForm(request.POST)
        if forms.is_valid():
            new_categories = Category2.objects.get(id=request.POST["categories"])
            new_title = request.POST.get('title')
            new_contents = request.POST.get('contents')
            new_ref_link = request.POST.get('ref_link')

            target.categories = new_categories
            target.title = new_title
            target.contents = new_contents
            target.ref_link = new_ref_link

            target.save()
            return redirect('notes:detail_page', target.id)

@login_required
def delete_page(request, id): # 개별글 삭제 : 작성된 글 삭제 페이지, Hard-Delete
    # GET : 삭제할 데이터 표기
    # POST
    # 데이터 유효성 검사 - 삭제 요청한 게시글 아이디 확인
    # 비지니스 로직 - 데이터 삭제 요청 재 확인 후 delete
    # 응답 - main-page로 redirect
    target = get_object_or_404(Note, id=id)
    if request.user != target.created_by:
        warn = messages.warning(request, "권한이 없습니다.")
        context = {
            'message': warn,
            'note': target,
        }
        return render(request, 'notes/detail.html', context)
    
    if request.method == "GET":
        context = {
            'note':target,
            'deleteorder': 'On'
        }
        return render(request, 'notes/detail.html', context)
    elif request.method == "POST":
        target.delete()
        return redirect('notes:main_page')

#tsearch_page, Taggit 모듈 사용으로 삭제(22.05.14)
#Taggit 제공 view 사용으로 변경(22.05.14)
class TagCloudTV(TemplateView):
    template_name= "taggit/tagsearch.html"

class TaggedObjectLV(ListView):
    template_name= "taggit/tagresult.html"
    model: Note

    def get_queryset(self):
        return Note.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

@login_required
def ctgr_view(request): # 생성된 카테고리 보기(22.05.12 추가)
    # 데이터 유효성 검사 - 로그인 유저 확인, 생성한 카테고리 확인
    # 비지니스 로직 - Category2써서 현재 유저가 생성한 카테고리를 확인
    # 응답 - 카테고리 리스트 표시
    current_user = request.user
    ctgy_manage_list = Category.objects.filter(created_by = current_user).order_by('id')
    ctgy2_manage_list = Category2.objects.filter(created_by = current_user).order_by('id')
        
    context = { 
        'category_manage_order':'On',
        'ctgy1':ctgy_manage_list, 
        'ctgy2':ctgy2_manage_list,
        }

    return render(request, 'notes/category.html', context)

@login_required
def ctgr1_create(request): # 카테고리 생성(22.05.12 추가)
    # GET : 재 렌더링
    # POST
    # 데이터 유효성 검사 - 로그인 유저 확인, 현재 생성된 카테고리 확인
    # 비지니스 로직 - 상위인지 하위인지 확인하고, 해당 신규 카테고리 생성
    # 응답 - main_page redirect
    if request.method=='GET':
        form = Ctgr1CreateForm()
        context = {
            'forms':form,
            'ctgypage':'1'
            }
        return render(request, 'notes/create.html', context)
    else:
        form = Ctgr1CreateForm(request.POST)

templates/notes/category.html
{% extends 'base.html' %}
{% block title %} Category {% endblock %}</title>

    {% block content %}
    <div description="Upper Bar" class="flex justify-around">
        <span class="block text-center text-xl font-bold"> Category </span>
        </span>
    </div>
    <br>
    {% if category_manage_order %}
    <div description="Management">
        <br>
        <span class="block text-center text-3xl bg-gray-200 p-2">
            상위 카테고리 목록
            <a class="inline bg-green-200 rounded-md text-xl" href="{% url 'notes:ct1_manage_create' %}">
            추가</a><br>
        </span>
        <br>
        {% for obj in ctgy1%}
            <span class="text-black m-1 p-1">{{obj.cate_name}}</span>
            <a class="inline-block bg-green-800 rounded-md text-white" href="{% url 'notes:ct1_manage_edit' obj.id %}">
                수정</a>
            <a class="inline-block bg-green-800 rounded-md m-0.5 text-white" href="{% url 'notes:ct1_manage_del' obj.id %}"> 
                삭제</a><br>
        {% endfor %}
        <br>
        <span class="block text-center text-3xl bg-gray-200 p-2">
            하위 카테고리 목록
            <a class="inline bg-green-200 rounded-md text-xl" href="{% url 'notes:ct2_manage_create' %}">
            추가</a><br>
        </span>
        <br>
        {% for obj in ctgy2%}
            <span class="inline-block bg-green-800 text-xs rounded-md text-white m-1 p-1">{{obj.P_cate_name}}</span>
            <span class="text-black">{{obj.cate2_name}}</span>
            <a class="inline-block bg-green-800 rounded-md m-0.5 text-white" href="{% url 'notes:ct2_manage_edit' obj.id %}">
                수정</a>
            <a class="inline-block bg-green-800 rounded-md m-0.5 text-white" href="{% url 'notes:ct2_manage_del' obj.id %}"> 
                삭제</a><br>
        {% endfor %}
    </div>
    {% endif %}

    {% if delete1order %}
        {% if message %}
        {{message}}
        {% endif %}
        <div description="Delete">
            정말로 삭제합니까? <br>
            대상 카테고리 : <span class="text-2xl">{{ctgy.cate_name}}</span>
            <form action="" method="post"> {%csrf_token%}
                <br><a class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2" href="{% url 'notes:ct_manage_view'%}">돌아가기</a>
                <div class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2">
                    <input type="submit" value="삭제하기">
                </div>
            </form>
        </div>
    {% endif %}

    {% if delete2order %}
    {% if message %}
    {{message}}
    {% endif %}
    <div class="Delete">
        정말로 삭제합니까? <br>
        대상 카테고리 : <span class="text-2xl">{{ctgy.cate2_name}}</span>
        <form action="" method="post"> {%csrf_token%}
            <br><a class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2" href="{% url 'notes:ct_manage_view'%}">돌아가기</a>
            <div class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2">
                <input type="submit" value="삭제하기">
            </div>
        </form>
    </div>
{% endif %}

    {% if list_view_page %}
    <div class="List">
        {% if ctgy_now %}
        <div class="block  bg-gray-200">
                <span class="inline-block rounded-md bg-gray-200 text-center text-xl ml-2 p-2"> 
                    선택한 카테고리 :<br></span>
                <span class="inline rounded-md text-white m-2 p-2 text-xl bg-blue-800">
                    {{ctgy_now}}</span>
                <a class="inline col-span-2 rounded-md text-white bg-green-800" href="javascript:window.history.back()">
                    뒤로 돌아가기</a>
                
        </div>
        {% endif %}
        <br>
        {% if ctgy_list %}
        <div class="Category2_List">
            <span class="block text-center text-3xl bg-gray-200">[카테고리 목록]</span><br>
            <div class="flex justify-evenly">
            {% for obj in ctgy_list %}
                <a class="text-sky-500 text-xl" href="{% url 'notes:Scategory_page' obj.cate2_name %}">
                    {{ obj.cate2_name }}</a>
            {% endfor %}
            </div>
        {% endif %}
        </div>
        <br>
        {% if note_page_list %}
        <div class="Note_List">
            <span class="block text-center text-3xl bg-gray-200">[해당 카테고리 글 목록]</span><br>
            <section class="block text-red-500 text-center">
                게시글은 한 페이지에 20개씩 표시됩니다.<br>
                가장 최신글이 위에 표기됩니다.
            </section>
            {% for object in note_page_list %}
                <li><a class="text-sky-500 text-2xl m-2" href="{% url 'notes:detail_page' object.id %}">{{ object.title|truncatechars:10 }}</a>
                    <br>{{ object.modified_at }}</li><br>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endif %}
    {% endblock %}

templates/notes/detail.html
{% extends 'base.html' %}
{% block title %} Detail {% endblock %}

{% block content %}
    {# 꾸미기 필요 #}
    {% if message %}
        {{message}}
    {% endif %}

    {% if deleteorder%}
        <span class="text-red-500">삭제한 데이터는 복구할 수 없습니다.<br>
        삭제를 진행할 게시글의 제목과 카테고리는 아래와 같습니다.</span>
    {% endif %}

    <h1 class="block text-3xl text-center m-2 p-2">{{ note.title }}<br></h1>
    <div class="border-2 border-gray-500">
        <div class="grid grid-cols-3">
            <span class="inline p-1 md-2">카테고리 : 
            <a class="inline bg-green-800 text-white text-xs rounded-md p-1" href="{% url 'notes:Scategory_page' note.categories %}">
            {{ note.categories }}</a></span>
            <br>
            <span class="inline text-right p-1 mr-4">작성자 : {{ note.created_by.nickname }}</span>
        </div>

        {% if not deleteorder%}
            <span class="p-1">참고 링크</span> :
            <a class="text-blue-500 p-1" href="{{note.ref_link}}">{{ note.ref_link }}</a>
        {% endif %}
    </div>
    <br>
    {% if not deleteorder %}
        <div class="border-2 border-gray-500 p-4">
            <pre>
{{ note.contents }}
            </pre> {# 노트의 본문 #}
        </div>
        <br>
        <div>
        <span class="block md-2">태그</span>
            {% for tag in note.tags.all %}
                <a class="inline bg-green-800 text-white text-xs rounded-md p-1" href="{% url 'notes:tagged_object_list' tag.name %}">
                {{ tag.name }}</a>
            {% endfor %}
        </div>
        <br>
        작성시간 : {{ note.created_at }}<br>
        수정시간 : {{ note.modified_at }}<br>
        <br>
        <div class="grid grid-cols-3 justify-items-stretch">
        {% if request.user == note.created_by %}
            <a class="inline bg-gray-400 text-black text-sm rounded-md mr-2 p-1 text-center" href="{% url 'notes:edit_page' note.id %}">
                수정하기</a>
            <a class="inline bg-gray-400 text-black text-sm rounded-md mr-2 p-1 order-last justify-self-end" href="{% url 'notes:delete_page' note.id %}">
                삭제하기</a>
        {% endif %}
        <a class="inline bg-gray-400 text-black text-sm rounded-md mr-2 p-1 text-center" href="javascript:window.history.back()">
            돌아가기</a>
        </div>
    {% endif %}

        {% if deleteorder %}
            <form action="" method="post"> {%csrf_token%}
            <div class="grid grid-cols-2 justify-items-stretch">
                <a class="inline bg-gray-400 text-black text-sm rounded-md p-1 order-last justify-self-end" href="{% url 'notes:detail_page' note.id %}">
                    돌아가기</a>
                <div class="inline bg-gray-400 text-black text-sm rounded-md p-1 justify-self-start">
                    <input type="submit" value="삭제하기">
                </div>
            </div>
            </form>
        {% endif %}
    <br>
{% endblock %}