config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from notes.views import index
"""
통합페이지 구성
1. 인덱스 페이지 : 뭐하는 페이지인지 간단한 설명, 로그인으로 넘어갈 수 있는 구조
2. 로그인 페이지
3. 로그아웃 페이지, 일정시간 후 자동으로 인덱스 페이지로 넘기기/html의 메타태그 사용
4. 노트 앱으로 접속
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('notes/', include('notes.urls', namespace = 'notes')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path("__reload__/", include("django_browser_reload.urls")),

    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

notes/urls.py
from django.urls import path
from .views import ctgr2_create, main_page, Pcategory_page, Scategory_page, \
    create_page, detail_page, edit_page, delete_page, \
    ctgr_view, ctgr1_create, ctgr1_edit, ctgr1_delete, \
    ctgr2_create, ctgr2_edit, ctgr2_delete
from .views import TagCloudTV, TaggedObjectLV

app_name = 'notes'

"""
필요한 페이지 
1. 로그인 후 보여줄 메인페이지 : 작성된 전체글, 부모 카테고리 지정 링크
2. 부모 카테고리 : 부모 카테고리에 포함된 모든 글 및 자식 카테고리 지정 링크
3. 자식 카테고리 : 자식 카테고리에 포함된 모든 글 링크
4. 글 쓰기 : 새로운 글 쓰기
5. 개별글 보기 : 작성된 글 상세보기 링크
6. 개별글 수정 : 작성된 글 수정 링크
7. 개별글 삭제 : 작성된 글 삭제 페이지, Hard-Delete
8. 태그별 보기 : 작성된 글 중에서 태그에 해당되는 글 리스트 출력
"""

urlpatterns = [
    # 기본 View 페이지
    path('main/', main_page, name='main_page'),
    path('category/<str:cate_name>', Pcategory_page, name='Pcategory_page'),
    path('category/category2/<str:cate2_name>', Scategory_page, name='Scategory_page'),
    
    # 노트 CRUD
    path('new/', create_page, name='create_page'),
    path('<int:id>/', detail_page, name='detail_page'),
    path('<int:id>/edit/', edit_page, name='edit_page'),
    path('<int:id>/delete/', delete_page, name='delete_page'),

    # 카테고리 CRUD
    path('ctgymanage/', ctgr_view, name='ct_manage_view'),
    path('ctgymanage/ctgr1/new/', ctgr1_create, name='ct1_manage_create'),
    path('ctgymanage/ctgr1/edit/<int:id>', ctgr1_edit, name='ct1_manage_edit'),
    path('ctgymanage/ctgr1/del/<int:id>', ctgr1_delete, name='ct1_manage_del'),
    path('ctgymanage/ctgr2/new/', ctgr2_create, name='ct2_manage_create'),
    path('ctgymanage/ctgr2/edit/<int:id>', ctgr2_edit, name='ct2_manage_edit'),
    path('ctgymanage/ctgr2/del/<int:id>', ctgr2_delete, name='ct2_manage_del'),

    #Taggit 모듈 사용, Tag 페이지 별도 구성
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>',TaggedObjectLV.as_view(), name='tagged_object_list'),
]

templates/taggit/tagresult.html
{% extends "base.html" %}
{% block title %}taggit_list{% endblock %}
{% block content %}
    <div description="Search Target">
        <span class="block text-center text-3xl bg-gray-200 m-2">
            <span class="inline-block bg-green-800 text-2xl rounded-md text-white m-1 p-1">'{{ tagname }}'</span>
            <span class="text-xl rounded-md m-1 p-1">태그 검색 결과</span>
        </span>
            본인이 작성한 글만 표기됩니다.
    </div>
    <br>
    <div>
    {% for post in object_list %}
    {% if post.created_by == request.user %}
        <li><a class="text-sky-500 text-2xl m-2" href="{% url 'notes:detail_page' post.id %}">
        {{post.title}}</a>{{ post.modified_at }}</li><br>
    {% endif %}
    {% endfor %}
    </div>
{% endblock %}

templates/taggit/tagsearch.html
{% extends 'base.html' %}

{% block title %}taggit_cloud{% endblock %}

{% block content %}
    <h1 class="block text-center text-2xl">Tag Cloud</h1>
    <br>
    사용자들의 태그를 볼 수 있습니다. 글은 확인할 수 없습니다.<br><br>

    <div description="tag-cloud" class="">
        {% load taggit_templatetags2_tags %}
        {% get_tagcloud as tags %}
        {% for tag in tags %}
        {% if tag.num_times != 0 %}
            <a href="{% url 'notes:tagged_object_list' tag.name %}">
                <span class="inline-block bg-green-800 rounded-full text-white m-1 p-1">
                    {{tag.name}}({{tag.num_times}})
                </span>
            </a>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}