accounts/urls.py
from django.urls import path

from .views import userlogin, userlogout, signup_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', userlogin, name='login'),
    path('logout/', userlogout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from notes.views import index
"""
통합페이지 구성
1. 인덱스 페이지 : 뭐하는 페이지인지 간단한 설명, 로그인으로 넘어갈 수 있는 구조
2. 로그인 페이지
3. 로그아웃 페이지, 일정시간 후 자동으로 인덱스 페이지로 넘기기/html의 메타태그 사용
4. 노트 앱으로 접속
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('notes/', include('notes.urls', namespace = 'notes')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path("__reload__/", include("django_browser_reload.urls")),

    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

notes/urls.py
from django.urls import path
from .views import ctgr2_create, main_page, Pcategory_page, Scategory_page, \
    create_page, detail_page, edit_page, delete_page, \
    ctgr_view, ctgr1_create, ctgr1_edit, ctgr1_delete, \
    ctgr2_create, ctgr2_edit, ctgr2_delete
from .views import TagCloudTV, TaggedObjectLV

app_name = 'notes'

"""
필요한 페이지 
1. 로그인 후 보여줄 메인페이지 : 작성된 전체글, 부모 카테고리 지정 링크
2. 부모 카테고리 : 부모 카테고리에 포함된 모든 글 및 자식 카테고리 지정 링크
3. 자식 카테고리 : 자식 카테고리에 포함된 모든 글 링크
4. 글 쓰기 : 새로운 글 쓰기
5. 개별글 보기 : 작성된 글 상세보기 링크
6. 개별글 수정 : 작성된 글 수정 링크
7. 개별글 삭제 : 작성된 글 삭제 페이지, Hard-Delete
8. 태그별 보기 : 작성된 글 중에서 태그에 해당되는 글 리스트 출력
"""

urlpatterns = [
    # 기본 View 페이지
    path('main/', main_page, name='main_page'),
    path('category/<str:cate_name>', Pcategory_page, name='Pcategory_page'),
    path('category/category2/<str:cate2_name>', Scategory_page, name='Scategory_page'),
    
    # 노트 CRUD
    path('new/', create_page, name='create_page'),
    path('<int:id>/', detail_page, name='detail_page'),
    path('<int:id>/edit/', edit_page, name='edit_page'),
    path('<int:id>/delete/', delete_page, name='delete_page'),

    # 카테고리 CRUD
    path('ctgymanage/', ctgr_view, name='ct_manage_view'),
    path('ctgymanage/ctgr1/new/', ctgr1_create, name='ct1_manage_create'),
    path('ctgymanage/ctgr1/edit/<int:id>', ctgr1_edit, name='ct1_manage_edit'),
    path('ctgymanage/ctgr1/del/<int:id>', ctgr1_delete, name='ct1_manage_del'),
    path('ctgymanage/ctgr2/new/', ctgr2_create, name='ct2_manage_create'),
    path('ctgymanage/ctgr2/edit/<int:id>', ctgr2_edit, name='ct2_manage_edit'),
    path('ctgymanage/ctgr2/del/<int:id>', ctgr2_delete, name='ct2_manage_del'),

    #Taggit 모듈 사용, Tag 페이지 별도 구성
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>',TaggedObjectLV.as_view(), name='tagged_object_list'),
]

templates/base.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.min.css' %}"/>
    <title>{% block title %}{% endblock %} || MyNote</title>
    {% tailwind_css %}
</head>

<body>
    
    <div class="flex flex-row">
        {% if request.user.is_authenticated %}
        <div class="sticky h-screen inset-y-0 left-1 w-52 ml-2 bg-gradient-to-b from-orange-200 to-blue-200">
            <br><br>
            <span class="block text-center text-3xl font-bold">
                <a href="{% url 'notes:main_page' %}">My Note</a></span>
                <span class="block text-center mt-4">
                    <span class="text-sm"></span>
                    <span class="text-lg font-bold">{{request.user.nickname}}</span>
                    <a class="text-xs m-1 p-1" href="{% url 'accounts:logout' %}">로그아웃</a>
                </span>
            <br><br>

            <a class="block m-1 p-1 text-xl" href="{% url 'notes:main_page' %}">홈</a>
            <a class="block m-1 p-1 text-xl" href="{% url 'notes:create_page' %}">글 쓰기</a>
            <a class="block m-1 p-1 text-xl" href="{% url 'notes:ct_manage_view' %}">카테고리 관리</a>
            <a class="block m-1 p-1 text-xl" href="{% url 'notes:tag_cloud' %}">태그 검색</a>
            <br>
            
        </div>
        {% endif %}

        <div class="w-full ml-2 mr-2 p-2">
            <span>
                {% block content %}
                {% endblock %}
            </span>
            {% if request.user.is_authenticated %}
                {% if note_page_list %}
                <span description="Pagination" class="block text-center">
                    {% if note_page_list.has_previous %}
                        <a href="?page=1">First</a>
                        <a href="?page={{note_list.previous_page_number}}">Previous</a>
                    {% endif %}

                    <span>{{ note_page_list.number }} of {{ note_page_list.paginator.num_pages }}</span>

                    {% if note_page_list.has_next %}
                        <a href="?page={{ note_list.next_page_number }}">Next</a>
                        <a href="?page={{ note_list.paginator.num_pages }}">Last</a>
                    {% endif %}
                </span>
                {% endif %}
            {% endif %}
            <br>
        </div>
    </div>
</body>
</html>

templates/index.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>방문을 환영합니다. || MyNote</title>
    {% tailwind_css %}
</head>

<body class="leading-normal tracking-normal">
    <div description="Positioner" class="flex items-stretch h-screen justify-center">
        <div description="Notification" class="self-center">
            <br>
            방문을 환영합니다.<br>
            로그인이 필요한 서비스로, 로그인을 해주세요.<br>
            <br>
            <a description="UserLogin" class="block bg-green-800 rounded-full text-white m-1 p-1 self-center text-white text-xl text-center" href="{% url 'accounts:login' %}">
                로그인하기</a>
            <a description="UserSignUp" class="block bg-green-800 rounded-full text-white m-1 p-1 self-center text-white text-xl text-center" href="{% url 'accounts:signup' %}">
                계정 만들기</a>
        </div>
    </div>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
    <h1 class="block text-center text-2xl">로그인</h1><br>
    <form action="" method="POST"> {% csrf_token %}
        <!-- <div>
            {{ form.as_ul }}
        </div> -->
        <div class="border-2 border-gray-200 rounded p-4 m-4 flex flex-col justify-center">
            <div class="text-grey-darker text-sm font-bold m-8">
            <span>{{ form.username.label }}</span><br>
            <span>{{ form.username }}</span>
            <br><br>
            <span>{{ form.password.label}}</span><br>
            <span>{{ form.password}}</span>
            </div>
        </div>
        <br>
        <div class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2">
            <input type="submit" value="로그인하기">
        </div>
    </form>
    <a class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2" href="{% url 'index' %}">돌아가기</a>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
    <h1 class="block text-center text-2xl">회원 가입</h1><br>
    <form action="" method="POST"> 
        {% csrf_token %}
        <!-- <div>
            {{ form.as_ul }}
        </div> -->
        <div class="border-2 border-gray-200 rounded p-4 m-4 flex flex-col justify-center">
            <div class="text-grey-darker text-sm font-bold m-8">
                <span class="text-center">{{ form.identifier.label }}  </span><br>
                <span class="">{{ form.identifier }}</span><br>

                <span class="">{{ form.password1.label }}</span><br>
                <span class="">{{ form.password1 }}</span><br>

                <span class="">{{ form.password2.label }}</span><br>
                <span class="">{{ form.password2 }}</span><br>

                <span class="">{{ form.nickname.label }}</span><br>
                <span class="">{{ form.nickname }}</span><br>

                <span class="">{{ form.username.label }}</span><br>
                <span class="">{{ form.username }}</span><br>

                <span class="">{{ form.email.label }}</span><br>
                <span class="">{{ form.email }}</span><br>

                <span class="">{{ form.phone.label }}</span><br>
                <span class="">{{ form.phone }}</span><br>
            </div>
        </div>
        <br>
        <div class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2">
            <input type="submit" value="계정 생성">
        </div>
        <a class="inline-block bg-gray-500 rounded-md text-white mt-4 p-2" href="{% url 'index' %}">돌아가기</a>
    </form>
    
{% endblock %}